ingress:
  # allows you to specify custom hosts
  customHosts:
    # specify your ngrok custom domain here
    # such as
    #    hook: "myuniqueid.ngrok.io
    # so that webhooks from, say, github.com, will work to your local laptop
    #hook: "hook.jx"
    hook: ""

kaniko:
  # lets support insecure docker registries so that we
  # can use the local docker-registry chart
  flags: "--insecure"
3e8b-197-29-137-174.ngrok.io
